### ISSUE TITLE
Problem in demo train_3_test_1

### ISSUE THREAD

**Issue by 1209657459** [YijunBao/Shallow-UNet-Neuron-Segmentation_SUNS#13]
The final output is this
`Initialization time: 0.7937037944793701 s
Initialization: 0.05836844444274902 s
data loading: 0.8330998420715332 s
temporal filtering: 0.09518313407897949 s
median computation: 0.1928389072418213 s
normalization: 0.08255314826965332 s
total per frame: 0.12358530362447102 ms
Pre-Processing time: 0.370849 s, 0.123616 ms/frame
CNN Infrence time: 0.336596 s, 0.112199 ms/frame
{'minArea': 17.0, 'avgArea': 100.0, 'thresh_pmap': 130, 'thresh_mask': 0.5, 'thresh_COM0': 1.5, 'thresh_COM': 3.0, 'thresh_IOU': 0.5, 'thresh_consume': 0.75, 'cons': 1}
separate Neurons         : Used  0.551084 s,  0.184371 ms/frame,    1589 segmented neurons.
unique_neurons1          : Used  0.267900 s,  0.089628 ms/frame,       1 segmented neurons.
group_neurons            : Used  0.011718 s,  0.003920 ms/frame,       1 segmented neurons.
piece_neurons_IOU        : Used  0.014430 s,  0.004828 ms/frame,       1 segmented neurons.
piece_neurons_consume    : Used  0.003538 s,  0.001184 ms/frame,       1 segmented neurons.
refine_seperate          : Used  0.000706 s,  0.000236 ms/frame,       1 segmented neurons.
Total time               : Used  0.851102 s,  0.284745 ms/frame,       1 segmented neurons.
Post-Processing time: 0.888099 s, 0.296033 ms/frame
Total time: 1.595544 s, 0.531848 ms/frame
{'Recall': 0, 'Precision': 0, 'F1': 0}`
I did not make any changes to the environment, code and data.
F1_train,Recall_train,Precision_train in Optimization_Info_{ }.mat are all 0.
The Masks in Output_Masks_CV0_YST_part{ }.mat are all 1, and the size is 1x120x88.
What could be the reason for this? I tried to rerun it several times and it still has the same result.

**Comment by 1209657459** [comment]
> Initialization time: 0.7937037944793701 s
Initialization: 0.05836844444274902 s
data loading: 0.8330998420715332 s
temporal filtering: 0.09518313407897949 s
median computation: 0.1928389072418213 s
normalization: 0.08255314826965332 s
total per frame: 0.12358530362447102 ms
Pre-Processing time: 0.370849 s, 0.123616 ms/frame
CNN Infrence time: 0.336596 s, 0.112199 ms/frame
{'minArea': 17.0, 'avgArea': 100.0, 'thresh_pmap': 130, 'thresh_mask': 0.5, 'thresh_COM0': 1.5, 'thresh_COM': 3.0, 'thresh_IOU': 0.5, 'thresh_consume': 0.75, 'cons': 1}
separate Neurons         : Used  0.551084 s,  0.184371 ms/frame,    1589 segmented neurons.
unique_neurons1          : Used  0.267900 s,  0.089628 ms/frame,       1 segmented neurons.
group_neurons            : Used  0.011718 s,  0.003920 ms/frame,       1 segmented neurons.
piece_neurons_IOU        : Used  0.014430 s,  0.004828 ms/frame,       1 segmented neurons.
piece_neurons_consume    : Used  0.003538 s,  0.001184 ms/frame,       1 segmented neurons.
refine_seperate          : Used  0.000706 s,  0.000236 ms/frame,       1 segmented neurons.
Total time               : Used  0.851102 s,  0.284745 ms/frame,       1 segmented neurons.
Post-Processing time: 0.888099 s, 0.296033 ms/frame
Total time: 1.595544 s, 0.531848 ms/frame
{'Recall': 0, 'Precision': 0, 'F1': 0}

**Comment by YijunBao** [comment]
I think the discussion has been redirected to https://github.com/YijunBao/Shallow-UNet-Neuron-Segmentation_SUNS/issues/12#issuecomment-1186844279
