### ISSUE TITLE
Version for volumetric data coming?

### ISSUE THREAD

**Issue by flmuk** [YijunBao/Shallow-UNet-Neuron-Segmentation_SUNS#6]
Good afternoon,
given the performance of SUNS indicated in the paper I wonder if there will be also a version coming for 3D videos, e.g. data with dimensions (T,Z,Y,X), or if this approach is restricted to 2D videos?
This would be great!

**Comment by YijunBao** [comment]
Thank you for your interest in SUNS. Unfortunately, we do not have the plan to extend SUNS to volumetric data in the near future. We only use SUNS in 2D videos.
