### ISSUE TITLE
Wrong ROIs input format: unfamiliar shape

### ISSUE THREAD

**Issue by DG1038286** [YijunBao/Shallow-UNet-Neuron-Segmentation_SUNS#9]
I generated ground truth marking masks on our data through the matlab version of [Caiman ](https://github.com/flatironinstitute/CaImAn) and I've set up our data by altering the given demo scripts. I'm able to generate sparse versions of the masks, but when I go to train the CNN, it gives me the following error:

```
Traceback (most recent call last):
  File "demo_train_CNN_params_1to3.py", line 176, in <module>
    generate_masks(video_input, file_mask, list_thred_ratio, dir_parent, Exp_ID)
  File "../..\suns\PreProcessing\generate_masks.py", line 56, in generate_masks
    experiment.separation_prep(redo=True)
  File "C:\Users\Advan\anaconda3\envs\suns\lib\site-packages\fissa\core.py", line 324, in separation_prep
    results[trial] = extract_func(inputs[trial])
  File "C:\Users\Advan\anaconda3\envs\suns\lib\site-packages\fissa\core.py", line 62, in extract_func
    base_masks = datahandler.rois2masks(rois, curdata)
  File "C:\Users\Advan\anaconda3\envs\suns\lib\site-packages\fissa\datahandler.py", line 98, in rois2masks
    raise ValueError('Wrong ROIs input format: unfamiliar shape.')
ValueError: Wrong ROIs input format: unfamiliar shape.
```

I've checked the dimensions of the masks and the input videos and they match the given conventions. Please, is there any guidance on this?

**Comment by YijunBao** [comment]
Did you only use the sparse version throughout the training? Actually, the sparse version is only used in optimizing post-processing parameters. When runing `generate_masks`, the mask files here should be non-sparse 3D array. The `GT Masks` folder should contain both the non-sparse and sparse versions of the masks. 
If this does not solve your problem, is there a way that you can share your masks with me?

**Comment by DG1038286** [comment]
The GT Masks folder contains both the sparse and non-sparse files (where sparse were generated from the generate_sparse_GT.py). Could I get your email?
